#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
EXP_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

RUN_ID="${RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)-vm32-local16-32-48}"
SESSION="${SESSION:-vm32-realworld-${RUN_ID}}"
RESULTS_ROOT="${RESULTS_ROOT:-${EXP_ROOT}/results}"
RUN_ROOT="${RUN_ROOT:-${RESULTS_ROOT}/${RUN_ID}}"
STATE_DIR="${RUN_ROOT}/state"
ENV_FILE="${STATE_DIR}/tmux.env"
mkdir -p "${STATE_DIR}"

{
  printf 'RUN_ID=%q\n' "${RUN_ID}"
  printf 'RESULTS_ROOT=%q\n' "${RESULTS_ROOT}"
  printf 'RUN_ROOT=%q\n' "${RUN_ROOT}"
  printf 'LOCAL_SIZES_GIB=%q\n' "${LOCAL_SIZES_GIB:-16 32 48}"
  printf 'CONFIGS=%q\n' "${CONFIGS:-off on tpp ours}"
  printf 'WORKLOADS=%q\n' "${WORKLOADS:-pr bc gups btree graph500 silo}"
  printf 'DROP_GUEST_CACHES=%q\n' "${DROP_GUEST_CACHES:-1}"
  printf 'COMPACT_GUEST_MEMORY=%q\n' "${COMPACT_GUEST_MEMORY:-1}"
  printf 'DROP_HOST_CACHES_BEFORE_VM_BOOT=%q\n' "${DROP_HOST_CACHES_BEFORE_VM_BOOT:-1}"
  printf 'DROP_HOST_CACHES_BEFORE_GUEST_RUN=%q\n' "${DROP_HOST_CACHES_BEFORE_GUEST_RUN:-1}"
  printf 'HOST_CPUS=%q\n' "${HOST_CPUS:-0-31}"
  printf 'GUEST_CPUS=%q\n' "${GUEST_CPUS:-32}"
  printf 'GUEST_NODE0_CPUS=%q\n' "${GUEST_NODE0_CPUS:-0-31}"
  printf 'FAST_HOST_NODE=%q\n' "${FAST_HOST_NODE:-0}"
  printf 'SLOW_HOST_NODE=%q\n' "${SLOW_HOST_NODE:-2}"
  printf 'MIGRATION_SLOW_MEM=%q\n' "${MIGRATION_SLOW_MEM:-128G}"
  printf 'ROOTFS_VIRTUAL_SIZE=%q\n' "${ROOTFS_VIRTUAL_SIZE:-120G}"
  printf 'TIMEOUT_SEC=%q\n' "${TIMEOUT_SEC:-21600}"
  printf 'OMP_THREADS=%q\n' "${OMP_THREADS:-32}"
  printf 'MGLRU_ENABLED=%q\n' "${MGLRU_ENABLED:-0x0007}"
  printf 'NUMA_SCAN_SIZE_MB=%q\n' "${NUMA_SCAN_SIZE_MB:-256}"
  printf 'NUMA_SCAN_PERIOD_MIN_MS=%q\n' "${NUMA_SCAN_PERIOD_MIN_MS:-1000}"
  printf 'LOCAL_FAULT_SCAN_PERIOD_MS=%q\n' "${LOCAL_FAULT_SCAN_PERIOD_MS:-1000}"
  printf 'LOCAL_FAULT_SCAN_SIZE_MB=%q\n' "${LOCAL_FAULT_SCAN_SIZE_MB:-64}"
  printf 'DISABLE_SWAP=%q\n' "${DISABLE_SWAP:-1}"
  printf 'PR_TRIALS=%q\n' "${PR_TRIALS:-8}"
  printf 'BC_TRIALS=%q\n' "${BC_TRIALS:-8}"
  printf 'GAPBS_GRAPH_SCALE=%q\n' "${GAPBS_GRAPH_SCALE:-29}"
  printf 'SILO_SCALE_FACTOR=%q\n' "${SILO_SCALE_FACTOR:-800000}"
  printf 'SILO_OPS_PER_WORKER=%q\n' "${SILO_OPS_PER_WORKER:-100000000}"
  printf 'LIBLINEAR_DATASET=%q\n' "${LIBLINEAR_DATASET:-kdd12}"
  printf 'LIBLINEAR_SOLVER=%q\n' "${LIBLINEAR_SOLVER:-6}"
  printf 'LIBLINEAR_THREADS=%q\n' "${LIBLINEAR_THREADS:-${OMP_THREADS:-32}}"
  printf 'FAULT_BUCKET_CONTROLLER_DIR=%q\n' "${FAULT_BUCKET_CONTROLLER_DIR:-/Serverless/iccd-git/design/fault_bucket_controller}"
  printf 'CONTROLLER_PORT=%q\n' "${CONTROLLER_PORT:-10165}"
  printf 'WINDOW_SEC=%q\n' "${WINDOW_SEC:-1}"
  printf 'CYCLE_WINDOW_MIN_SEC=%q\n' "${CYCLE_WINDOW_MIN_SEC:-5}"
  printf 'CYCLE_WINDOW_MAX_SEC=%q\n' "${CYCLE_WINDOW_MAX_SEC:-20}"
  printf 'LOCAL_RATE=%q\n' "${LOCAL_RATE:-1}"
  printf 'CONTROLLER_POLICY=%q\n' "window-cdf-gap"
  printf 'START_CDF_GAP_PPM=%q\n' "${START_CDF_GAP_PPM:-200000}"
  printf 'WINDOW_CONSECUTIVE=%q\n' "1"
  printf 'STOP_CAPACITY_RATIO_THRESHOLD=%q\n' "${STOP_CAPACITY_RATIO_THRESHOLD:-0.9}"
  printf 'LOCAL_NODE=%q\n' "${LOCAL_NODE:-0}"
  printf 'REMOTE_NODE=%q\n' "${REMOTE_NODE:-1}"
  printf 'MIGRATION_ENABLED_PATH=%q\n' "${MIGRATION_ENABLED_PATH:-/sys/kernel/mm/numa_balancing/migration_enabled}"
  printf 'REBOOT_AFTER_STAGE=%q\n' "${REBOOT_AFTER_STAGE:-0}"
  printf 'DISABLE_SMT=%q\n' "${DISABLE_SMT:-0}"
  printf 'RESTORE_SMT=%q\n' "${RESTORE_SMT:-0}"
  printf 'STOP_VM_WAIT_SEC=%q\n' "${STOP_VM_WAIT_SEC:-90}"
  printf 'STOP_VM_ON_SUCCESS=%q\n' "${STOP_VM_ON_SUCCESS:-1}"
  printf 'STOP_VM_ON_FAILURE=%q\n' "${STOP_VM_ON_FAILURE:-1}"
  printf 'STOP_VM_ON_EXIT=%q\n' "${STOP_VM_ON_EXIT:-1}"
  printf 'RESUME=%q\n' "${RESUME:-1}"
  printf 'CLEAN_SCRIPTS=%q\n' "${CLEAN_SCRIPTS:-1}"
  printf 'STAGE_WORKLOADS=%q\n' "${STAGE_WORKLOADS:-1}"
  printf 'DELETE_VM_IMAGES=%q\n' "${DELETE_VM_IMAGES:-1}"
} > "${ENV_FILE}"

CMD="set -a; source $(printf '%q' "${ENV_FILE}"); set +a; exec $(printf '%q' "${SCRIPT_DIR}/run_vm_sweep_host.sh")"
tmux new-session -d -s "${SESSION}" -c "${EXP_ROOT}" "${CMD}"
printf 'session=%s\nrun_root=%s\nenv=%s\n' "${SESSION}" "${RUN_ROOT}" "${ENV_FILE}"
