#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export RUN_ID="${RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)-vm32-controller-local16-32-48}"
export SESSION="${SESSION:-vm32-controller-${RUN_ID}}"
export LOCAL_SIZES_GIB="${LOCAL_SIZES_GIB:-16 32 48}"
export CONFIGS="${CONFIGS:-controller_0x2}"
export WORKLOADS="${WORKLOADS:-pr bc gups graph500 btree redis_uniform redis_ycsb_a faster_uniform faster_ycsb_a}"

export FAULT_BUCKET_CONTROLLER_DIR="${FAULT_BUCKET_CONTROLLER_DIR:-/Serverless/iccd-git/design/fault_bucket_controller}"
export CONTROLLER_PORT="${CONTROLLER_PORT:-10165}"
export CONTROLLER_WINDOW_SEC="${CONTROLLER_WINDOW_SEC:-5}"
export CONTROLLER_LOCAL_RATE="${CONTROLLER_LOCAL_RATE:-5}"
export CONTROLLER_REMOTE_RATE="${CONTROLLER_REMOTE_RATE:-5}"
export CONTROLLER_LOCAL_FAULT_SCAN_PERIOD_MS="${CONTROLLER_LOCAL_FAULT_SCAN_PERIOD_MS:-1000}"
export CONTROLLER_LOCAL_FAULT_SCAN_SIZE_MB="${CONTROLLER_LOCAL_FAULT_SCAN_SIZE_MB:-256}"
export CONTROLLER_REMOTE_FAULT_SCAN_PERIOD_MS="${CONTROLLER_REMOTE_FAULT_SCAN_PERIOD_MS:-${CONTROLLER_LOCAL_FAULT_SCAN_PERIOD_MS}}"
export CONTROLLER_REMOTE_FAULT_SCAN_SIZE_MB="${CONTROLLER_REMOTE_FAULT_SCAN_SIZE_MB:-${CONTROLLER_LOCAL_FAULT_SCAN_SIZE_MB}}"
export CONTROLLER_MIN_LOCAL_PAGES="${CONTROLLER_MIN_LOCAL_PAGES:-1024}"
export CONTROLLER_MIN_REMOTE_PAGES="${CONTROLLER_MIN_REMOTE_PAGES:-1024}"
export CONTROLLER_CONSECUTIVE_EFFECTIVE="${CONTROLLER_CONSECUTIVE_EFFECTIVE:-2}"
export CONTROLLER_CONSECUTIVE_NO_IMPROVE="${CONTROLLER_CONSECUTIVE_NO_IMPROVE:-2}"
export CONTROLLER_RESTART_REMOTE_SHARE_THRESHOLD="${CONTROLLER_RESTART_REMOTE_SHARE_THRESHOLD:-1.2}"
export CONTROLLER_CONSECUTIVE_RESTART="${CONTROLLER_CONSECUTIVE_RESTART:-2}"
export CONTROLLER_RESTART_GRACE_WINDOWS="${CONTROLLER_RESTART_GRACE_WINDOWS:-1}"
export CONTROLLER_NUMA_BALANCING_ON="${CONTROLLER_NUMA_BALANCING_ON:-2}"
export CONTROLLER_NUMA_BALANCING_OFF="${CONTROLLER_NUMA_BALANCING_OFF:-0}"

exec "${SCRIPT_DIR}/run_vm_sweep_tmux.sh"
