#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
KERNEL_SOURCE="${KERNEL_SOURCE:-${REPO_ROOT}/linux}"
KERNEL_BUILD="${KERNEL_BUILD:-${REPO_ROOT}/linux-global-build}"
CONFIG="${KERNEL_BUILD}/.config"

[[ -x "${KERNEL_SOURCE}/scripts/config" ]] || {
	printf 'missing kernel config tool: %s\n' "${KERNEL_SOURCE}/scripts/config" >&2
	exit 2
}
[[ -f "${CONFIG}" ]] || {
	printf 'missing kernel build config: %s\n' "${CONFIG}" >&2
	exit 2
}

# Keep the NUMA controller sysfs ABI, but remove instrumentation that is not
# part of the evaluated policy.
disabled=(
	DEBUG_MISC
	DEBUG_INFO
	DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT
	DEBUG_INFO_DWARF4
	DEBUG_INFO_DWARF5
	GDB_SCRIPTS
	KGDB
	KGDB_KDB
	KDB_KEYBOARD
	DYNAMIC_DEBUG
	DYNAMIC_DEBUG_CORE
	DEBUG_FS
	DEBUG_FS_ALLOW_ALL
	BOOT_PRINTK_DELAY
	FTRACE
	TRACING
	GENERIC_TRACER
	CONTEXT_SWITCH_TRACER
	FUNCTION_TRACER
	FUNCTION_GRAPH_TRACER
	STACK_TRACER
	SCHED_TRACER
	HWLAT_TRACER
	MMIOTRACE
	FTRACE_SYSCALLS
	TRACER_SNAPSHOT
	TRACE_EVENT_INJECT
	BOOTTIME_TRACING
	KPROBE_EVENTS
	KPROBES
	KRETPROBES
	OPTPROBES
	FUNCTION_ERROR_INJECTION
	UPROBE_EVENTS
	BPF_EVENTS
	BLK_DEV_IO_TRACE
	SYNTH_EVENTS
	HIST_TRIGGERS
	SCHEDSTATS
	SCHED_INFO
	SCHED_STACK_END_CHECK
	TASK_DELAY_ACCT
	TASKSTATS
	TASK_XACCT
	TASK_IO_ACCOUNTING
	PSI
	PSI_DEFAULT_DISABLED
	DEBUG_PREEMPT
	SLUB_DEBUG
	PAGE_POISONING
	LRU_GEN_STATS
	FRAME_POINTER
	UNWINDER_FRAME_POINTER
	STACK_VALIDATION
	KALLSYMS
	KALLSYMS_ALL
	KALLSYMS_SELFTEST
	STACKTRACE
	PROFILING
	MAGIC_SYSRQ
	MAGIC_SYSRQ_SERIAL
	DEBUG_BUGVERBOSE
	DEBUG_WX
	X86_DEBUG_FPU
	EARLY_PRINTK
	EARLY_PRINTK_USB
	EARLY_PRINTK_DBGP
	EARLY_PRINTK_USB_XDBC
	LOCKUP_DETECTOR
	SOFTLOCKUP_DETECTOR
	HARDLOCKUP_DETECTOR
	DETECT_HUNG_TASK
	DETECT_HUNG_TASK_BLOCKER
	KVM
	KVM_INTEL
	KVM_AMD
	IDLE_PAGE_TRACKING
	PM_DEBUG
	PM_ADVANCED_DEBUG
	PM_SLEEP_DEBUG
	PM_TRACE
	ACPI_DEBUGGER
	ACPI_DEBUGGER_USER
	ACPI_DEBUG
	FW_LOADER_DEBUG
	MEMTEST
	IOSF_MBI_DEBUG
	BLK_DEBUG_FS
	BT_DEBUGFS
	CFG80211_DEBUGFS
	MAC80211_DEBUGFS
	MMC_CB710
	CB710_CORE
	CB710_DEBUG_ASSUMPTIONS
	SCSI_IPR_TRACE
	MLX4_DEBUG
	ATH9K_COMMON_DEBUG
	ATH9K_DEBUGFS
	ATH9K_HTC_DEBUGFS
	WIL6210_DEBUGFS
	ATH10K_DEBUGFS
	ATH11K_DEBUGFS
	IWLEGACY_DEBUGFS
	IWLWIFI_DEBUGFS
	RTW88_DEBUG
	RTW88_DEBUGFS
	RTW89_DEBUG
	RTW89_DEBUGMSG
	RTW89_DEBUGFS
	IEEE802154_CA8210_DEBUGFS
	WWAN_DEBUGFS
	MEDIA_TEST_SUPPORT
	V4L_TEST_DRIVERS
	SMS_SIANO_DEBUGFS
	THINKPAD_ACPI_DEBUGFACILITIES
	OCFS2_DEBUG_MASKLOG
	NFS_DEBUG
	SUNRPC_DEBUG
	CIFS_DEBUG
	PUNIT_ATOM_DEBUG
	SAMPLES
	NOTIFIER_ERROR_INJECTION
	PM_NOTIFIER_ERROR_INJECT
	HWPOISON_INJECT
	TEST_BPF
	SCSI_DEBUG
	EFI_TEST
	COMEDI_TEST
	COMEDI_TESTS
	COMEDI_TESTS_EXAMPLE
	COMEDI_TESTS_NI_ROUTES
	USB_TEST
	USB_EHSET_TEST_FIXTURE
	USB_LINK_LAYER_TEST
	USB_SERIAL_DEBUG
	SPI_LOOPBACK_TEST
	XZ_DEC_TEST
	TEST_POWER
	PKCS7_TEST_KEY
	ACPI_EC_DEBUGFS
	WILCO_EC_DEBUGFS
	SND_SOC_SOF_INTEL_TOPLEVEL
	SND_SOC_SOF_AMD_TOPLEVEL
	SND_SOC_SOF_DEBUG_PROBES
	SND_SOC_SOF_HDA_PROBES
)

for symbol in "${disabled[@]}"; do
	"${KERNEL_SOURCE}/scripts/config" --file "${CONFIG}" --disable "${symbol}"
done

"${KERNEL_SOURCE}/scripts/config" --file "${CONFIG}" --enable UNWINDER_ORC

make -s -C "${KERNEL_SOURCE}" O="${KERNEL_BUILD}" olddefconfig

for symbol in "${disabled[@]}"; do
	if grep -Eq "^CONFIG_${symbol}=(y|m)$" "${CONFIG}"; then
		printf 'failed to disable CONFIG_%s\n' "${symbol}" >&2
		exit 1
	fi
done

for symbol in NUMA_BALANCING_MT LRU_GEN SYSFS; do
	if ! grep -q "^CONFIG_${symbol}=y$" "${CONFIG}"; then
		printf 'required CONFIG_%s is not enabled\n' "${symbol}" >&2
		exit 1
	fi
done

printf 'production kernel config updated: %s\n' "${CONFIG}"
